#!/usr/bin/env bash
# Regenerate supabase/full-schema.sql by concatenating every
# migration in supabase/migrations/ in chronological order. The
# resulting file is the same SQL `supabase db push` would run on a
# fresh database — useful for bootstrapping a new environment, for
# disaster recovery, or as a one-stop reference for the whole schema.
#
# Day-to-day schema changes still go in NEW migration files under
# supabase/migrations/. This script just rebundles them; it does NOT
# generate new migrations or apply anything to a live database.
#
# Run from the repo root:   npm run schema:bundle

set -euo pipefail

cd "$(dirname "$0")/.."

OUT="supabase/full-schema.sql"
MIG_DIR="supabase/migrations"

if [[ ! -d "$MIG_DIR" ]]; then
  echo "error: $MIG_DIR not found — run from the repo root" >&2
  exit 1
fi

# Header banner — explains what this file is, when to use it, when
# NOT to use it. Mirrors the prose in the file's preamble.
{
  cat <<'HEADER'
-- ╔══════════════════════════════════════════════════════════════════╗
-- ║  VANO — full Supabase schema (consolidated)                       ║
-- ║                                                                    ║
-- ║  This file is the chronological concatenation of every migration  ║
-- ║  in supabase/migrations/, in the same order Supabase applies them ║
-- ║  on `supabase db push`. Running this file end-to-end on a fresh   ║
-- ║  Postgres database produces the exact schema the live site uses:  ║
-- ║                                                                    ║
-- ║    • Auth-linked tables (profiles, student_profiles, roles)        ║
-- ║    • Talent + community board (community_posts, listing requests)  ║
-- ║    • Conversations + messages (with realtime + RLS)                ║
-- ║    • Hire flow (hire_requests, hire_agreements)                    ║
-- ║    • Vano Match (ai_find_requests, scouted_freelancers, scoring)   ║
-- ║    • Vano Pay (vano_payments, escrow, deadline-aware auto-release) ║
-- ║    • Digital sales (sales_deals + per-deal + target milestones)    ║
-- ║    • Reviews (reviews + review→Vano Match feedback signal)         ║
-- ║    • Analytics + feature flags + crons                             ║
-- ║                                                                    ║
-- ║  When to use this file:                                            ║
-- ║    • Bootstrapping a brand-new Supabase project from scratch       ║
-- ║    • Onboarding a new dev environment without `supabase db push`   ║
-- ║    • Disaster recovery / point-in-time restore                     ║
-- ║    • A one-stop reference for reading the whole schema             ║
-- ║                                                                    ║
-- ║  When NOT to use it:                                               ║
-- ║    • Day-to-day schema changes — write a new migration in          ║
-- ║      supabase/migrations/ instead. This file is regenerated by    ║
-- ║      `npm run schema:bundle` and overwritten on every release;    ║
-- ║      hand-edits are lost.                                          ║
-- ║    • Production deploys — let Supabase apply migrations            ║
-- ║      individually so the migration history table stays accurate.  ║
-- ║                                                                    ║
-- ║  Generated from: supabase/migrations/                              ║
-- ║  Migrations included: see SECTION HEADERS below                    ║
-- ╚══════════════════════════════════════════════════════════════════╝

-- The migrations were authored over many months and assume each one
-- runs against the schema state produced by the previous ones (no
-- migration here is idempotent on its own). The order below — the
-- alphabetical filename order Supabase enforces — is what makes the
-- whole sequence converge.

HEADER

  for f in $(ls "$MIG_DIR"/*.sql | sort); do
    name=$(basename "$f" .sql)
    printf '\n\n-- ════════════════════════════════════════════════════════════════════\n'
    printf -- '-- ▼ %s\n' "$name"
    printf -- '-- ════════════════════════════════════════════════════════════════════\n\n'
    cat "$f"
  done
} > "$OUT"

count=$(grep -c "^-- ▼" "$OUT")
size=$(du -h "$OUT" | cut -f1)
lines=$(wc -l < "$OUT")
echo "Bundled $count migrations into $OUT ($lines lines, $size)"
